mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
]

mysite/news/urls.py
from django.urls import path

from . import views

app_name = 'news'
urlpatterns = [
    path('', views.listNews, name='listNews'),
    path('search/result', views.searchNews, name='searchNews'),
    path('search', views.searchView, name='search'),
    path('together', views.listNewsOnHTML, name='listNewsOnHTML'),
    path('together/result', views.searchNewsOnHTML, name='searchNewsOnHTML'),
]

mysite/news/models.py
from django.db import models

# Create your models here.
class SearchRequests(models.Model):
    query = models.CharField(max_length=250, primary_key=True)
    dateAdded = models.DateField()

class SearchResults(models.Model):
    headline = models.TextField()
    link = models.URLField()
    source = models.CharField(max_length=50)
    request = models.ManyToManyField(SearchRequests)

mysite/news/views.py
import datetime
import json

from django.core import serializers
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse

from newsapi import NewsApiClient
import praw

from .models import SearchRequests, SearchResults

# Create your views here.

EXP_DATE = datetime.date(2020, 1, 1)


def listNewsOnHTML(request):
    results = []

    results.extend(getRedditResults())
    results.extend(getNewsAPIResults())

    context = {
        "results": results
    }

    return render(request, 'news/combined.html', context)


def search(keyword):
    results = []
    try:
        # if keyword has already been queried, data will be retrieved from database
        fromDB = SearchRequests.objects.get(pk=keyword)
        entryDate = fromDB.dateAdded

        if entryDate > EXP_DATE:
            results = list(fromDB.searchresults_set.all().values(
                'headline', 'link', 'source'))
        else:
            # if data in database is old, call APIs and save again
            raise AssertionError('old')

    except (SearchRequests.DoesNotExist, AssertionError) as e:
        # save query in database
        reqEntry = SearchRequests(
            query=keyword, dateAdded=datetime.datetime.today().date())
        reqEntry.save()

        if str(e) == 'old':
            # delete old news articles from database
            SearchResults.objects.filter(request=keyword).delete()

        results.extend(searchRedditResults(keyword, reqEntry))
        results.extend(searchNewsAPIResults(keyword, reqEntry))
    return results

def searchNewsOnHTML(request):
    results = []
    if request.method == 'POST':
        keyword = request.POST['kw']
        results = search(keyword)

    context = {
        'results': results
    }

    return render(request, 'news/result.html', context)


def searchView(request):
    return render(request, 'news/index.html')


def listNews(request):
    results = []

    results.extend(getRedditResults())
    results.extend(getNewsAPIResults())

    return JsonResponse(results, safe=False)


def searchNews(request):
    results = []
    if request.method == 'POST':
        keyword = request.POST['kw']

        results = search(keyword)

    return JsonResponse(results, safe=False)


def getRedditResults():
    """
    Gets results from Reddit API with only the fields required
    """
    results = []
    try:
        reddit = praw.Reddit(client_id="4ZQq_6IHGR6t6A",
                            client_secret="AmKTDcjfrcxU6yjpSIu4uY7DvCU",
                            user_agent="testscript by /u/fornewsapi")


        for submission in reddit.subreddit("news").top(limit=10):
            results.append({
                'headline': submission.title,
                'link': submission.url,
                'source': 'reddit'
            })
    except Exception:
        pass

    return results


def getNewsAPIResults():
    """
    Gets results from News API with only the fields required
    """
    results = []

    try:
        newsapi = NewsApiClient(api_key='cb682c4048944cd1a9f17e88bb3ad67f')

        us_articles = newsapi.get_top_headlines(category="general", page_size=10)

        for news in us_articles['articles']:
            results.append({
                'headline': news['title'],
                'link': news['url'],
                'source': 'newsAPI'
            })
    except Exception:
        pass

    return results


def searchRedditResults(keyword, reqEntry):
    """
    Searches for results containing keyword from Reddit API with only the fields required
    """
    results = []

    try:
        reddit = praw.Reddit(client_id="4ZQq_6IHGR6t6A",
                            client_secret="AmKTDcjfrcxU6yjpSIu4uY7DvCU",
                            user_agent="testscript by /u/fornewsapi")


        for submission in reddit.subreddit("news").search(keyword, limit=10):
            submissionDict = {'headline': submission.title,
                            'link': submission.url,
                            'source': 'reddit'
                            }
            results.append(submissionDict)

            redditEntry = SearchResults(**submissionDict)
            redditEntry.save()
            redditEntry.request.add(reqEntry)
    except Exception:
        pass

    return results


def searchNewsAPIResults(keyword, reqEntry):
    """
    Searches for results containing keyword from News API with only the fields required
    """
    results = []

    try:
        newsapi = NewsApiClient(api_key='cb682c4048944cd1a9f17e88bb3ad67f')

        for news in newsapi.get_top_headlines(q=keyword, category='general', page_size=10)['articles']:
            newsDict = {'headline': news['title'],
                        'link': news['url'],
                        'source': "newsapi"
                        }
            results.append(newsDict)

            newsEntry = SearchResults(**newsDict)
            newsEntry.save()
            newsEntry.request.add(reqEntry)
    except Exception:
        pass

    return results

mysite/news/templates/news/combined.html
<html>

<head>
    <meta charset="utf-8">
    <title></title>
</head>

<style>
    html,
    body {
        height: 100%;
        width: 100%;
        margin: 0;
    }

    form {
        border: 0.5px solid gray;
        padding: 50px;
        margin: auto;
        text-align: center;
    }

    form> :nth-child(4) {
        margin: 5px;
    }

    ul {
        list-style-type: none;
        border-bottom: 0.5px solid gray;
    }
</style>

<body>
    <form action="{% url 'news:searchNewsOnHTML'%}" method="POST">
        {% csrf_token %}
        <label for="kw" required>Type the phrase you want to search for:</label><br>
        <input name="kw" id="kw"><br>
        <input type="submit" value="Search">
    </form>
    <div id="results">
        {% for i in results %}
        <ul>
            <li>{{i.headline}}</li>
            <li><a href="{{i.link}}">{{i.link}}</a></li>
            <li>{{i.source}}</li>
        </ul>
        {% endfor %}
    </div>
</body>

</html>

mysite/news/templates/news/index.html
<html>

<head>
    <meta charset="utf-8">
    <title></title>
</head>

<style>
    html,
    body {
        height: 100%;
        width: 100%;
        margin: 0;
    }

    body {
        display: flex;
    }

    form {
        border: 0.5px solid gray;
        padding: 50px;
        margin: auto;
        text-align: center;
    }

    form > :nth-child(4) {
        margin: 5px;
    }
</style>

<body>
    
        <form action="{% url 'news:searchNews'%}" method="POST">
            {% csrf_token %}
            <label for="kw" required>Type the phrase you want to search for:</label><br>
            <input name="kw" id="kw"><br>
            <input type="submit" value="Search">
        </form>
    
</body>

</html>

mysite/news/templates/news/result.html
<html>

<head>
    <meta charset="utf-8">
    <title></title>
</head>

<style>
    html,
    body {
        height: 100%;
        width: 100%;
        margin: 0;
    }

    ul {
        list-style-type: none;
        border-bottom: 0.5px solid gray;
    }

    a {
        text-decoration: none;
        display: inline-block;
        padding: 8px 16px;
    }

    a.previous:hover {
        background-color: #ddd;
        color: black;
    }

    .previous {
        background-color: #f1f1f1;
        color: black;
    }
</style>

<body>
    <a href="{% url 'news:listNewsOnHTML'%}" class="previous">Go back</a>
    <div id="results">
        {% for i in results %}
        <ul>
            <li>{{i.headline}}</li>
            <li><a href="{{i.link}}">{{i.link}}</a></li>
            <li>{{i.source}}</li>
        </ul>
        {% endfor %}
    </div>
</body>

</html>